# Generated by Django 5.2.4 on 2025-07-08 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WashStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='washstation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('wash_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='autowash.washstation')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('wash_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='autowash.washstation')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=100)),
                ('car_number', models.CharField(max_length=10)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('employe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autowash.employee')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autowash.service')),
                ('wash_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='autowash.washstation')),
            ],
        ),
    ]
