version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8090:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: carwash
      POSTGRES_USER: employ
      POSTGRES_PASSWORD: admin2025
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
networks:
  default:
    driver: bridge
