name: Django DRF CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: employ
          POSTGRES_PASSWORD: admin2025
          POSTGRES_DB: carwash

    env:
      CI: true
      DB_HOST: postgres
      DB_PORT: 5432

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h $DB_HOST -p $DB_PORT -U employ; do
            echo "Waiting for postgres…"
            sleep 1
          done

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test
